### ISSUE TITLE
Format of data in folder 'data

### ISSUE THREAD

**Issue by 1ncredibleM1nd** [alexsoin/pepelac#31]
Hi, Alex, i found this template useful but i need answe for my question. 
How can i use data for mapping in my .twig files ? 

It's JSON  ? And i need have name of data file with .js extension and my .twig must have the same name ?

**Comment by alexsoin** [comment]
Вот тут находится пример расположения данных в файле [site.js](https://github.com/alexsoin/pepelac/blob/master/src/data/site.js#L2) и вывод данных в файле [index.twig](https://github.com/alexsoin/pepelac/blob/master/src/views/index.twig#L21)
